### ISSUE TITLE
如何配置只用脚手架？

### ISSUE THREAD

**Issue by doterme** [choerodon/choerodon-front-boot#1]
不想去连接后台API，只想用这个脚手架，请问如何配置？

**Comment by HughHzWu** [comment]
不行，boot不是单纯的脚手架，而是开源项目猪齿鱼的前端引擎。

**Comment by doterme** [comment]
那我如果要用脚手架，要怎么做呢

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
