### ISSUE TITLE
打包的时候内存溢出的问题

### ISSUE THREAD

**Issue by zhangwenan** [choerodon/choerodon-front-boot#2]
以下这个项目，也存在打包的时候溢出的问题。
https://github.com/choerodon/choerodon-front

我将package.json中的依赖版本从0.10.4升级成
"choerodon-front-boot": "0.10.5"

重新npm install, 再npm start，就会报错。

**Comment by zhangwenan** [comment]
@binjie09

**Comment by binjie09** [comment]
需要确保有至少4G以上剩余内存，子模块中不能有安装的node_modules，已经在start命令中把node堆栈内存调整到了4096M，理论上应该不会溢出了。

**Comment by udhayamgit** [comment]
📦  building modules (10988/10990 modules)DEPRECATION WARNING on line 24 of /Users/udhayamp/freshconsole/choerodon/choerodon-front/node_modules/@choerodon/boot/lib/containers/components/c7n/header/style/Logo.scss:
The operation `#3F51B5 minus #0f1216` is deprecated and will be an error in future versions.
Consider using Sass's color functions instead.
http://sass-lang.com/documentation/Sass/Script/Functions.html#other_color_functions

📦  building modules (10994/10994 modules)
<--- Last few GCs --->

[97025:0x103000000]   303283 ms: Mark-sweep 1312.8 (1418.9) -> 1312.8 (1418.9) MB, 652.2 / 0.0 ms  allocation failure GC in old space requested
[97025:0x103000000]   303957 ms: Mark-sweep 1312.8 (1418.9) -> 1312.8 (1409.9) MB, 673.3 / 0.0 ms  last resort GC in old space requested
[97025:0x103000000]   304817 ms: Mark-sweep 1312.8 (1409.9) -> 1312.8 (1401.9) MB, 854.4 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x359c3be25879 <JSObject>
    2: replace(this=0x359ca9318421 <Very long string[10762980]>,0x359cf58cfa71 <JSRegExp <String[80]: \bn?exports\.push\(\[module\.i, \\?"(.+?\})(?:\\?\\n)?\\?", \\?"\\?"(?:\]\)|,\{)>>,0x359ca9318449 <JSFunction src.replace (sfi = 0x359c8b6fdf49)>)
    3: /* anonymous */ [/Users/udhayamp/freshconsole/choerodon/choerodon-front/node_modules/webpack-theme-color-replacer/src/AssetsExtractor.js:~48] ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::Runtime_StringBuilderConcat(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 6: 0x12a50b0042fd
 7: 0x12a50b068f5e
 8: 0x12a50b0686c0
 9: 0x12a50bd15f7e
10: 0x12a50b00535f
✨  Done in 305.36s.

**Comment by udhayamgit** [comment]
📦  building modules (10988/10990 modules)DEPRECATION WARNING on line 24 of /Users/udhayamp/freshconsole/choerodon/choerodon-front/node_modules/@choerodon/boot/lib/containers/components/c7n/header/style/Logo.scss:
The operation `#3F51B5 minus #0f1216` is deprecated and will be an error in future versions.
Consider using Sass's color functions instead.
http://sass-lang.com/documentation/Sass/Script/Functions.html#other_color_functions

📦  building modules (10994/10994 modules)
<--- Last few GCs --->

[97025:0x103000000]   303283 ms: Mark-sweep 1312.8 (1418.9) -> 1312.8 (1418.9) MB, 652.2 / 0.0 ms  allocation failure GC in old space requested
[97025:0x103000000]   303957 ms: Mark-sweep 1312.8 (1418.9) -> 1312.8 (1409.9) MB, 673.3 / 0.0 ms  last resort GC in old space requested
[97025:0x103000000]   304817 ms: Mark-sweep 1312.8 (1409.9) -> 1312.8 (1401.9) MB, 854.4 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x359c3be25879 <JSObject>
    2: replace(this=0x359ca9318421 <Very long string[10762980]>,0x359cf58cfa71 <JSRegExp <String[80]: \bn?exports\.push\(\[module\.i, \\?"(.+?\})(?:\\?\\n)?\\?", \\?"\\?"(?:\]\)|,\{)>>,0x359ca9318449 <JSFunction src.replace (sfi = 0x359c8b6fdf49)>)
    3: /* anonymous */ [/Users/udhayamp/choerodon/choerodon-front/node_modules/webpack-theme-color-replacer/src/AssetsExtractor.js:~48] ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::Runtime_StringBuilderConcat(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 6: 0x12a50b0042fd
 7: 0x12a50b068f5e
 8: 0x12a50b0686c0
 9: 0x12a50bd15f7e
10: 0x12a50b00535f
✨  Done in 305.36s.
